### ISSUE TITLE
The host（mouse）reference files

### ISSUE THREAD

**Issue by duphiler** [ruppinlab/CSI-Microbes-identification#15]
I found that the host reference file for The PathSeq files is only human, if possible, can you provide the reference file for mouse?

**Comment by wir963** [comment]
Hey @duphiler, 

We didn't experiment with detection of bacterial UMIs from scRNA-seq of mice at all so I'm hesitant to officially support that.  It should work in theory but we didn't explore that. If you're interested, here's a link to [GATK documentation on how to build your own reference files](https://gatk.broadinstitute.org/hc/en-us/articles/360037224472-PathSeqPipelineSpark). 

Best, Welles
