### ISSUE TITLE
Missing samtools-env.yaml file

### ISSUE THREAD

**Issue by luisa-cusick** [ruppinlab/CSI-Microbes-identification#16]
Hi, 

I am trying to build the PathSeq microbe files and the conda environment file referenced here https://github.com/ruppinlab/CSI-Microbes-identification/blob/5d6aef9330f72b72c2137cf5cb8e3bd33c8e7b45/build-PathSeq-microbe-files/Snakefile#L92 is missing. It looks like there should be a conda environment file pathogen-discovery-rules/envs/samtools-env.yaml. Can you please share this conda file, or let me know if I should update the path with a different .env file?

Thanks!

Luisa

**Comment by wir963** [comment]
Hey Luisa, 

Can you confirm that you followed the git submodule initialization step in the README? Specifically the below steps. 

This repository uses two [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) ([RNA-snakemake-rules](https://github.com/ruppinlab/RNA-snakemake-rules) and [pathogen-discovery-rules](https://github.com/ruppinlab/pathogen-discovery-rules)), which need to be initialized and fetched using the following commands.
```
cd CSI-Microbes-identification
git submodule init
git submodule update
```

Best, Welles

**Comment by luisa-cusick** [comment]
Hi Welles,

Yes, I did initialize and update the git submodules. There is no `samtools-env.yaml` in either of those repos, but maybe I should modify `build-PathSeq-microbe-files/Snakefile` to use a different env file. Let me know what works in your environment!

Thanks for your help,

Luisa

**Comment by wir963** [comment]
Hey Luisa, 

Apologies for the delays - I had a spree of conferences and this slipped. I merged in a PR that should fix your issue. Please let me know if it doesn't. 

Best, Welles
