### ISSUE TITLE
Error of "git submodule update"

### ISSUE THREAD

**Issue by jingyu9603** [ruppinlab/CSI-Microbes-identification#18]
Hi,

Thank you very much for developing such a wonderful tool. I have been trying to use CSI-Microbes to analyze my scRNA data recently, but I encountered some problems when pulling the git submodules. The following is my code and the error message:
```linux
$ git submodule update
fatal: remote error: upload-pack: not our ref a39f05a9211c931e844bd5c1a3d5ed445627b4be
Fetched in submodule path 'pathogen-discovery-rules', but it did not contain a39f05a9211c931e844bd5c1a3d5ed445627b4be. Direct fetching of that commit failed. 
````
It appears to be caused by modifications in the submodule. Could you please verify this?

Thanks!

Jing Yu

**Comment by wir963** [comment]
Ahhh thanks for catching that Jing Yu! It should work now!
