### ISSUE TITLE
Running tools for other sequencing method

### ISSUE THREAD

**Issue by ChoiJi-Hye** [ruppinlab/CSI-Microbes-identification#9]
Hi,.
I have 3' 10x chromium 5' 10x chromium, 3' CITE-seq, 5' CITE-seq data.
Is there any problem with using the tool on my data or should I change the options in this scripts?

I would appreciate your help.

**Comment by wir963** [comment]
Hey @ChoiJi-Hye, 

Are you running into any issues? I've run the code on 10x 3' and 5' scRNA-seq datasets so it should definitely work for that. I haven't run any CITE-seq data but you should be able to separate the RNA reads from the "protein" reads (the protein reads should be uninformative for microbes). 

Best, Welles

**Comment by ChoiJi-Hye** [comment]
Thank you for quick response. @wir963 

No. It worked well on my data, and the results are in.
However, the number of infected cells was smaller than expected, so I asked if there was an option to produce the best results.

If you have any advice later, please reply to me.
I'll leave the issue open for this, but you can close this issue if you want.
Thank you for your help. :)

Best regards.
ChoiJi-Hye

**Comment by wir963** [comment]
Hey @ChoiJi-Hye , 

I'm finalizing an updated manuscript for this project and I'll drop a link when that's available (hopefully in the next week or two). I think that manuscript will provide some clarifications and guidelines for different scRNA-seq technologies. Also once that's done, I'll have a little more time on my hands and I'm happy to discuss your results and dive into the options that you're using, etc. and give personalized suggestions. 

Best, Welles

**Comment by ChoiJi-Hye** [comment]
Thank you so much for your help. @wir963 

I sent an email to your NIH account titled "CSI-microbes's result questoin" to discuss my data further. ( I just found out there's a typo in the title. If you search my email, you'll have to look out for typos.)
Would it be okay for you to look at my email and provide some assistance? 
Thank you very much.

Best regards.
ChoiJi-Hye

**Comment by wir963** [comment]
Hey ChoiJi-Hye,

Can you resend your email to my gmail account (wir963)? I don’t have access to my NIH email anymore (I’ll update the README shortly).

Best, Welles
